version: '3'

services:
  server:
    depends_on:
      - db
    build: .
    volumes:
      - /app/node_modules
      - .:/app
    environment:
      - HOST=http://localhost
      - PORT=8080
      - DEBUG=true
      - DB_NAME=mysql
      - DB_USER=root
      - DB_HOST=db
      - DB_DRIVER=mysql
      - DB_PASSWORD=example
    ports:
      - "8080:8080"
    restart: unless-stopped
    
  db:
    image: 'mysql'
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      - MYSQL_ROOT_PASSWORD=example

